#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        sh "cd invoice && chmod +x gradlew"
        sh "cd invoice && ./gradlew clean --no-daemon"
    }


    stage('backend tests') {
        try {
            sh "cd invoice && ./gradlew test -PnodeInstall --no-daemon"
        } catch(err) {
            throw err
        } finally {
            junit '**/build/**/TEST-*.xml'
        }
    }

    stage('packaging') {
        sh "cd invoice && ./gradlew bootWar -x test -Pprod -PnodeInstall --no-daemon"
        archiveArtifacts artifacts: '**/build/libs/*.war', fingerprint: true
    }


    def dockerImage
    stage('build docker') {
        sh "cp -R invoice/src/main/docker invoice/build/"
        sh "cp invoice/build/libs/invoice-*-SNAPSHOT.war invoice/build/docker/"
        dockerImage = docker.build("${env.DOCKER_USER}/ecommerce-invoice", 'invoice/build/docker')
    }

    stage('publish docker') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-login') {
            dockerImage.push 'latest'
        }
    }
}
