# Provision AWS EKS cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: e-commerce-2
  type: core.Directory
  children:
  - name: aws-e-commerce-2
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: eu-west-1
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: e-commerce-2
  type: core.Directory
  children:
  - name: aws-cloudformation-e-commerce-2
    type: udm.Environment
    members:
    - Infrastructure/e-commerce-2/aws-e-commerce-2
    - Infrastructure/e-commerce-2/aws-e-commerce-2/eks-cloudformation