apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: e-commerce-2
  type: core.Directory
  children:

  - name: EKS-LAMBDA
    type: core.Directory
    children:
    ### create S3 bucket ###
    - name: e-commerce-2-lambda-bucket
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: s3-bucket-e-commerce-2-lambda
          type: aws.s3.BucketSpec
          bucketName: e-commerce-2-lambda
          region: eu-west-1
    ### upload the artifacts to S3 bucket ###
    - name: e-commerce-2-lambda-artifacts
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-lambda-artifacts
          type: aws.s3.File
          file: !file ../cloudformation/cfn-secret-provider.zip
          acl: bucket-owner-full-control
          scanPlaceholders: false
# Provision EKS cluster using Cloudformation templates
  - name: EKS-CLOUDFORMATION
    type: core.Directory
    children:
    - name: e-commerce-2-cloudformation-eks-user
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-eks-user
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-user.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: e-commerce-2
            UserStackName: e-commerce-2-eks-user
            S3BucketPrefix: e-commerce-2-lambda
    - name: e-commerce-2-cloudformation-eks-vpc
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-eks-vpc
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-vpc.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: e-commerce-2
            VPCStackName: e-commerce-2-eks-vpc
            AvailabilityZones: eu-west-1a, eu-west-1b
    - name: e-commerce-2-cloudformation-eks-master
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-eks-master
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-master.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: e-commerce-2
            VPCStackName: e-commerce-2-eks-vpc
    - name: e-commerce-2-cloudformation-eks-workers
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-eks-workers
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-workers.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: e-commerce-2
            VPCStackName: e-commerce-2-eks-vpc
            UserStackName: e-commerce-2-eks-user
            ClusterStackName: e-commerce-2-eks-master
            ClusterName: e-commerce-2-master
            NodeGroupName: e-commerce-2
    - name: e-commerce-2-k8s-configmap
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: e-commerce-2-aws-auth
          type: k8s.ResourcesFile
          file: !file ../kubernetes/aws-auth-cm.yaml
          delimiters: "## ##"

  - name: K8S
    type: core.Directory

# Provision K8s namespace
    children:
    - name: e-commerce-2-namespace
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: xl-demo
          type: k8s.NamespaceSpec
          namespaceName: 'xl-demo'