apiVersion: xl-release/v1
kind: Templates
spec:
- name: malaka-123
  type: xlrelease.Folder
  children:
  - name: malaka-123-destroy
    type: xlrelease.Release
    description: |
      This XL Release template shows how to undeploy an application, based on microservices architecture, to AWS EKS using XL Deploy.
    tags:
    - AWS
    - EKS
    - malaka-123
    scriptUsername: !value XL_RELEASE_USERNAME
    scriptUserPassword: !value XL_RELEASE_PASSWORD
    phases:
    - name: Undeploy Application
      type: xlrelease.Phase
      tasks:
      - name: Undeploy stateless services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy registry svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-registry
        - name: Undeploy invoice svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-invoice
        - name: Undeploy notification svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-notification
        - name: Undeploy store svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-store
      - name: Undeploy stateful services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy invoice mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-invoice-mysql
        - name: Undeploy store mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-store-mysql
        - name: Undeploy notification mongodb svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/malaka-123/aws-eks-malaka-123/malaka-123-notification-mongodb