# Provision AWS EKS cluster
apiVersion: xl-deploy/v1beta1
kind: Infrastructure
spec:
- name: e-commerce
  type: core.Directory
  children:
  - name: aws-e-commerce
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: us-east-1
---
apiVersion: xl-deploy/v1beta1
kind: Environments
spec:
- name: e-commerce
  type: core.Directory
  children:
  - name: aws-e-commerce-cloudformation
    type: udm.Environment
    members:
    - Infrastructure/e-commerce/aws-e-commerce/eks-cloudformation