# Provision AWS EKS cluster
apiVersion: xl-deploy/v1beta1
kind: Infrastructure
spec:
- name: malaka
  type: core.Directory
  children:
  - name: aws-malaka
    type: aws.Cloud
    accesskey: !value AWSAccessKey
    accessSecret: !value AWSAccessSecret
    children:
    - name: eks-cloudformation
      type: aws.cloudformation.Stack
      region: us-east-1
---
apiVersion: xl-deploy/v1beta1
kind: Environments
spec:
- name: malaka
  type: core.Directory
  children:
  - name: aws-malaka-cloudformation
    type: udm.Environment
    members:
    - Infrastructure/malaka/aws-malaka/eks-cloudformation