apiVersion: xl-deploy/v1beta1
kind: Applications
spec:
- name: malaka
  type: core.Directory
  children:

# Provision EKS cluster using Cloudformation templates
    - name: EKS-CLOUDFORMATION
      type: core.Directory
      children:
      - name: malaka-cloudformation-eks-user
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: malaka-eks-user
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-user.yaml
            capabilities:
            - CAPABILITY_IAM
            - CAPABILITY_NAMED_IAM
            inputVariables:
              ProjectName: malaka
              UserStackName: malaka-eks-user
      - name: malaka-cloudformation-eks-vpc
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: malaka-eks-vpc
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-vpc.yaml
            capabilities:
            - CAPABILITY_IAM
            - CAPABILITY_NAMED_IAM
            inputVariables:
              ProjectName: malaka
              VPCStackName: malaka-eks-vpc
              AvailabilityZones: us-east-1a, us-east-1b
      - name: malaka-cloudformation-eks-master
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: malaka-eks-master
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-master.yaml
            capabilities:
            - CAPABILITY_IAM
            - CAPABILITY_NAMED_IAM
            inputVariables:
              ProjectName: malaka
              VPCStackName: malaka-eks-vpc
      - name: malaka-cloudformation-eks-workers
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: malaka-eks-workers
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-workers.yaml
            capabilities:
            - CAPABILITY_IAM
            - CAPABILITY_NAMED_IAM
            inputVariables:
              ProjectName: malaka
              VPCStackName: malaka-eks-vpc
              UserStackName: malaka-eks-user
              ClusterStackName: malaka-eks-master
              ClusterName: malaka-master
              NodeGroupName: malaka
      - name: malaka-k8s-configmap
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: malaka-aws-auth
            type: k8s.ResourcesFile
            file: !file kubernetes/aws-auth-cm.yaml
            delimiters: "## ##"

    - name: K8S
      type: core.Directory

# Provision K8s namespace
      children:
      - name: malaka-namespace
        type: udm.Application
        children:
        - name: '1.0.0'
          type: udm.DeploymentPackage
          deployables:
          - name: xl-demo
            type: k8s.NamespaceSpec
            namespaceName: 'xl-demo'