#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        XL_VALUE_BUILD_ID = "1.0.${env.BUILD_ID}"

        XL_DEPLOY_URL = "http://xl-deploy:4516"
        XL_DEPLOY_CREDENTIALS = credentials("xld-credentials")
    }

    stages {
        stage ("checkout") {
            steps {
                checkout scm
            }
        }
        stage ("check java") {
            steps {
                sh "java -version"
            }
        }
        stage ("clean") {
            steps {
                sh "cd notification && chmod +x ./gradlew"
                sh "cd notification && ./gradlew clean --no-daemon"
            }
        }
        stage ("backend tests") {
            steps {
                try {
                    sh "cd notification && ./gradlew test -PnodeInstall --no-daemon"
                } catch(err) {
                    throw err
                } finally {
                    junit '**/build/**/TEST-*.xml'
                }
            }
        }
        stage ("packaging") {
            steps {
                sh "cd notification && ./gradlew bootWar -x test -Pprod -PnodeInstall --no-daemon"
                archiveArtifacts artifacts: '**/build/libs/*.war', fingerprint: true
            }
        }


        stage ("build and publish docker") {
            steps {
                script {
                    def dockerImage
                    stage ("build docker") {
                        sh "cp -R notification/src/main/docker notification/build/"
                        sh "cp notification/build/libs/*.war notification/build/docker/"
                        dockerImage = docker.build('<your-dockerhub-user>/ecommerce-notification', 'notification/build/docker')
                    }
                    stage ("publish docker") {
                        docker.withRegistry('https://index.docker.io/v1/', 'docker-login') {
                            dockerImage.tag("1.0.${env.BUILD_ID}")
                            dockerImage.push("1.0.${env.BUILD_ID}")
                        }
                    }
                }
            }
        }


        stage ("push xld package for notification") {
            steps {
                sh "cd notification && ./gradlew clean  sourcesForRelease -PimageTag=1.0.${env.BUILD_ID} --no-daemon"
                sh "./xlw apply -f xebialabs/xld-kubernetes-notification-app.yaml"
            }
        }

    }
}
