apiVersion: xl-deploy/v1beta1
kind: Applications
spec:
- name: ECOMMERCE
  type: core.Directory
  children:
    - name: EKS-PROVISION
      type: core.Directory
      children:
      - name: e-commerce-cloudformation-eks-user
        type: udm.Application
        children:
        - name: '1.0'
          type: udm.DeploymentPackage
          deployables:
          - name: eks-user
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-user.yaml
      - name: e-commerce-cloudformation-eks-vpc
        type: udm.Application
        children:
        - name: '1.0'
          type: udm.DeploymentPackage
          deployables:
          - name: eks-vpc
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-vpc.yaml
      - name: e-commerce-cloudformation-eks-master
        type: udm.Application
        children:
        - name: '1.0'
          type: udm.DeploymentPackage
          applicationDependencies:
            e-commerce-cloudformation-eks-vpc: "[1.0,1.0]"
          undeployDependencies: true
          orchestrator:
            - sequential-by-dependency
          deployables:
          - name: eks-master
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-master.yaml
      - name: e-commerce-cloudformation-eks-workers
        type: udm.Application
        children:
        - name: '1.0'
          type: udm.DeploymentPackage
          applicationDependencies:
            e-commerce-cloudformation-eks-master: "[1.0,1.0]"
            e-commerce-cloudformation-eks-user: "[1.0,1.0]"
          undeployDependencies: true
          orchestrator:
            - sequential-by-dependency
          deployables:
          - name: eks-workers
            type: aws.cloudformation.Template
            file: !file cloudformation/eks-workers.yaml
      - name: e-commerce-k8s-configmap
        type: udm.Application
        children:
        - name: '1.0'
          type: udm.DeploymentPackage
          deployables:
          - name: aws-auth
            type: k8s.ResourcesFile
            file: !file aws-auth-cm.yaml